<a href="https://colab.research.google.com/github/yuryychayka09-byte/Data_Analytics-/blob/main/Individual_Quest_for_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Завдання 1: Імпорт бібліотек та перевірка версій

In [1]:
import pandas as pd
import numpy as np

In [2]:
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 2.2.3
NumPy: 2.1.3


Завдання 2: Зчитування CSV та head/tail

In [5]:
df = pd.read_csv('/content/drive/MyDrive/data_dictionary_songs.csv')
print("Перші 3 рядки:")
print(df.head(3))
print("Останні 3 рядки:")
print(df.tail(3))

Перші 3 рядки:
     column    type                                        description
0  track_id  string                                    Unique track id
1     genre  string  pop / hiphop / edm / rock / latin / rnb / coun...
2    energy   float                               AUDIO: energy (0-10)
Останні 3 рядки:
         column type                                        description
18  streams_3yr  int  TARGET (regression): total streams after 3 yea...
19  slow_burner  int  TARGET (binary): 1 if half-life > 150 days (a ...
20       is_hit  int    TARGET (binary): 1 if top-10% by 3-year streams


In [4]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


 Завдання 3: Перелік колонок

In [6]:
cols = df.columns
print("Назви колонок:", cols)
print("Тип змінної:", type(cols))

Назви колонок: Index(['column', 'type', 'description'], dtype='object')
Тип змінної: <class 'pandas.core.indexes.base.Index'>


Завдання 4: Масив із парних чисел

In [7]:
arr = np.arange(2, 21, 2)   # перші 10 парних
print("Масив:", arr)
print("Сума:", arr.sum())
print("Середнє:", arr.mean())
print("Мінімум:", arr.min())
print("Максимум:", arr.max())
print("×3:", arr * 3)

Масив: [ 2  4  6  8 10 12 14 16 18 20]
Сума: 110
Середнє: 11.0
Мінімум: 2
Максимум: 20
×3: [ 6 12 18 24 30 36 42 48 54 60]


Завдання 5: Двовимірний масив 3x3

In [8]:
arr2d = np.random.randint(1, 11, (3,3))
print("Масив 3x3:\n", arr2d)
print("Сума по стовпцях:", arr2d.sum(axis=0))
print("Сума по рядках:", arr2d.sum(axis=1))

Масив 3x3:
 [[9 7 3]
 [1 2 9]
 [9 7 3]]
Сума по стовпцях: [19 16 15]
Сума по рядках: [19 12 19]


Завдання 7: Монтування Google Drive та порівняння типів

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
df2 = pd.read_csv('/content/drive/MyDrive/data_dictionary_songs.csv')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   column       21 non-null     object
 1   type         21 non-null     object
 2   description  21 non-null     object
dtypes: object(3)
memory usage: 636.0+ bytes


У наборі даних переважають числові типи, зокрема float та int. Така структура є типовою для аудіометричних показників та статистики стрімінгу, оскільки більшість характеристик (енергія, валентність, танцювальність, тривалість треку, кількість прослуховувань) мають кількісне вираження. Це забезпечує можливість проведення статистичного аналізу та побудови моделей прогнозування на основі числових ознак.

Додаткове завдання

In [11]:
# Комбінований ноутбук
df = pd.read_csv('/content/drive/MyDrive/data_dictionary_songs.csv')

print("Перші рядки:\n", df.head())
print("Розмірність:", df.shape)
df.info()
print(df.describe())

# Масив із числової колонки
energy_array = df['energy'].to_numpy()
print("Середнє значення energy:", energy_array.mean())

Перші рядки:
          column    type                                        description
0      track_id  string                                    Unique track id
1         genre  string  pop / hiphop / edm / rock / latin / rnb / coun...
2        energy   float                               AUDIO: energy (0-10)
3       valence   float                   AUDIO: positivity/valence (0-10)
4  danceability   float                         AUDIO: danceability (0-10)
Розмірність: (21, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   column       21 non-null     object
 1   type         21 non-null     object
 2   description  21 non-null     object
dtypes: object(3)
memory usage: 636.0+ bytes
          column type      description
count         21   21               21
unique        21    3               21
top     track_id  int  Unique track id
freq   

KeyError: 'energy'

In [12]:
import pandas as pd, numpy as np

print(pd.__version__)
print(np.__version__)

df=pd.read_csv('/content/drive/MyDrive/data_dictionary_songs.csv')
print(df.head(3))
print(df.tail(3))

c=df.columns
print(c)
print(type(c))

arr=np.arange(2,21,2)
print(arr)
print(arr.sum(),arr.mean(),arr.min(),arr.max())
print(arr*3)

a2=np.random.randint(1,11,(3,3))
print(a2)
print(a2.sum(axis=0))
print(a2.sum(axis=1))

from google.colab import drive
drive.mount('/content/drive')
df2=pd.read_csv('/content/drive/MyDrive/data_dictionary_songs.csv')
df2.info()

df=pd.read_csv('/content/drive/MyDrive/data_dictionary_songs.csv')
print(df.head())
print(df.shape)
df.info()
print(df.describe())

x=np.array([10,20,30,40,50])
print(x.mean())


2.2.3
2.1.3
     column    type                                        description
0  track_id  string                                    Unique track id
1     genre  string  pop / hiphop / edm / rock / latin / rnb / coun...
2    energy   float                               AUDIO: energy (0-10)
         column type                                        description
18  streams_3yr  int  TARGET (regression): total streams after 3 yea...
19  slow_burner  int  TARGET (binary): 1 if half-life > 150 days (a ...
20       is_hit  int    TARGET (binary): 1 if top-10% by 3-year streams
Index(['column', 'type', 'description'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
[ 2  4  6  8 10 12 14 16 18 20]
110 11.0 2 20
[ 6 12 18 24 30 36 42 48 54 60]
[[9 9 3]
 [3 6 4]
 [1 9 8]]
[13 24 15]
[21 13 18]
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries,